import React, { useState } from 'react';
import MHidden from '../../components/@mui-extend/MHidden';
import DesktopRoadmap from './DesktopRoadmap';
import IPadRoadmap from './IPadRoadmap';
import IPhoneRoadmap from './IPhoneRoadmap';

// ----------------------------------------------------------------------------------

const data = [
  {
    id: 1,
    title: 'designing',
    image: 'roadmap_dino_1.png',
    content: 'Starting off designing all 8000 Dripping Dino’s to go above and beyond every expectation. Our aim is to deliver the most exceptional looking and aesthetically pleasing NFT artworks in the world. We want to make each Dino look unique and stand out in its own way, that is why we have made sure to create over 200+ different types of traits of the highest quality.'
  },
  {
    id: 2,
    title: 'minting',
    image: 'roadmap_dino_2.png',
    content: 'Two whitelisted Private sales will start off the mint with a total of 2000 NFT’s, our Public sale will consist of the remaining 6000 pieces. You will be able to mint from our own website, all details surrounding the minting process will be shared on our website and Discord. Make sure you only use the links we send and promote on our socials. The security of our holders is our top priority, we highly recommend that you report any scams to our mod team.'
  },
  {
    id: 3,
    title: 'dao',
    image: 'roadmap_dino_3.png',
    content: 'We at Dripping Dino’s are making sure that we are constructing a utility based NFT economy that produces continuous value for holders. That is why we have opted to  develop a DAO which will support the project and will help create and fund all future plans and collections. The token that will fuel the DAO ecosystem will be our native token called DRIPPY ($DRIP). It will be issued to our holders who stake the Dino NFT’s with our primary financial institution, Dino Capital. People who stake their NFT can earn a daily x amount of $DRIP tokens. We will implement additional institutions to our DAO besides the Dino capital, such as our Pawnshop, our  Fractional NFT fund and the DRIP Liquidity Pool. These will all serve a specific role within our ecosystem and help support the value of $DRIP and keep providing value and utility to our NFT holders.'
  },
  {
    id: 4,
    title: 'charity',
    image: 'roadmap_dino_4.png',
    content: 'We are creating a charity to provide a helping hand to people in need without compromising the needs of our holders. We want to give back in a sustainable way and make an impact in the world while using this incredible technology. Dripping Dino’s will pledge to donate 100.000 USD worth of clothing to our own charity in the first week of minting. We will continue to donate meaningful amounts (generated by our DAO) every quarter of the year. These charity donations will be broadcasted and shown to our community, to document the legitimacy of our promises.'
  },
  {
    id: 5,
    title: 'fashion',
    image: 'roadmap_dino_5.png',
    content: 'We want to stay true to our name Dripping Dino’s, that is why we will set up our own unique designer brand. The brand will make sure that you\'re not only dripping online but also in the real world. We have already set up some big partnerships in the designer world with people who will help us deliver the most exclusive and premium quality clothing out there. All profits from our merch will be directed back into the DAO to support the project, which will benefit all holders.'
  },
];

// --------------------------------------------------------------------------------

export default function Roadmap() {
  const [selectedPosition, setSelectedPosition] = useState(0);

  return (
    <>
      <MHidden width="mdDown">
        <DesktopRoadmap
          data={data}
          selectedPosition={selectedPosition}
          setSelectedPosition={setSelectedPosition}
        />
      </MHidden>
      <MHidden width="mdUp">
        <MHidden width="smDown">
          <IPadRoadmap
            data={data}
            selectedPosition={selectedPosition}
            setSelectedPosition={setSelectedPosition}
          />
        </MHidden>
        <MHidden width="smUp">
          <IPhoneRoadmap
            data={data}
            selectedPosition={selectedPosition}
            setSelectedPosition={setSelectedPosition}
          />
        </MHidden>
      </MHidden>
    </>

  );
}