import React from 'react';
import { Stack, Typography, Box } from '@mui/material';

export default function IPhoneDao() {
  return (
    <Box mx={3} mt={14}>
      <Box>
        <Typography fontSize={20} fontWeight={700} textTransform="uppercase">
          Dao
        </Typography>
        <Typography fontSize={16} mt={1} sx={{ color: '#E0E0E0' }}>
          The DAO will be a self-sustaining ecosystem, which means that a large portion of the profits generated by Dripping Dino’s and others collections will be reinvested in the main and future Dino projects. The remaining profits will be split up into multiple branches which will include the Charity funds, Future giveaways (NFT’s consisting of DD and other trending projects!), designing/producing Dripping Dino’s merch (based on the NFT’s!) and much more.
        </Typography>
      </Box>

      <Stack mt={8} spacing={3}>
        <Box>
          <Box component="img" alt="dao_hero" src="/assets/images/dao_hero.png" fullWidth />
        </Box>

        <Stack direction="row" justifyContent="space-between" spacing={3}>
          <Box width="50%">
            <Box component="img" alt="dao_1" src="/assets/images/dao_1.png" fullWidth />
          </Box>
          <Box width="50%">
            <Box component="img" alt="dao_2" src="/assets/images/dao_2.png" fullWidth />
          </Box>
        </Stack>

        <Stack direction="row" justifyContent="space-between" spacing={3}>
          <Box width="50%">
            <Box component="img" alt="dao_cross" src="/assets/images/dao_cross.png" fullWidth />
          </Box>
          <Box width="50%">
            <Box component="img" alt="dao_3" src="/assets/images/dao_3.png" fullWidth />
          </Box>
        </Stack>
      </Stack>
    </Box>
  );
}