import React from 'react';
import { Typography, Box } from '@mui/material';

export default function DesktopCharity() {
  return (
    <Box position="relative" pt={10} height="100vh">
      <Box position="absolute" top={150} width="100%" zIndex={5}>
        <Typography fontSize={48} fontWeight={700} textTransform="uppercase" textAlign="center">
          Charity&volunteering
        </Typography>
      </Box>
      <Box position="absolute" top={350} ml={20} zIndex={5} width="35%">
        <Typography fontSize={20} mt={5}>
          We are creating a charity to provide a helping hand to people in need without compromising the needs of our holders. We want to give back in a sustainable way and make an impact in the world while using this incredible technology. Dripping Dino’s will pledge to donate 100.000 USD worth of clothing to our own charity in the first week of minting. We will continue to donate meaningful amounts (generated by our DAO) every quarter of the year. These charity donations will be broadcasted and shown to our community, to document the legitimacy of our promises.
        </Typography>
      </Box>
      {/* earth */}
      <Box
        component="img"
        src="/assets/images/earth.png"
        alt="earth"
        width={1200}
        position="absolute"
        right={0}
        top={80}
        zIndex={1}
      />
      {/* dinosaurs */}
      <Box
        component="img"
        src="/assets/images/twin_dinos.png"
        alt="twin_dinos"
        position="absolute"
        zIndex={2}
        right={220}
        top={250}
        width={700}
      />
      {/* pink_shadow */}
      <Box
        component="img"
        src="/assets/images/pink_shadow.png"
        alt="pink_shadow"
        width={1200}
        position="absolute"
        right={20}
        top={80}
        zIndex={3}
        sx={{ opacity: 0.5 }}
      />
      {/* blur_black_bar */}
      <Box
        component="img"
        src="/assets/images/blur_black_bar.png"
        alt="blur_black_bar"
        width={1500}
        position="absolute"
        right={0}
        top={620}
        zIndex={4}
      />
    </Box>
  );
}